### ISSUE TITLE
Grouped outputs

### ISSUE THREAD

**Issue by sq4bja** [lkankowski/arduino-multi-relay#3]
Is it possible to add grouped outputs assigned to one input?
Ex. INPUT 1 is assigned to output 2 and 3. High state on INPUT 1 sends high state to outputs 2 and 3.
If INPUT 4 is assigned to OUTPUT 2, changing state will only change one assigned output (OUTPUT 2), not all grouped to INPUT 1 (only OUTBUT 2, not OUTPUT 3).
If INPUT 1 is High, and OUTPUT 2 and 3 also, and after that INPUT 4 changing state to high - OUTPUT 2 is low, OUTPUT 3 is high. If i change INPUT 1 state to LOW, onlu OUTPUT 3 change state to LOW (OUTPUT 2 is LOW - from INPUT 4).
Wow.... I thing, you understand this :)

**Comment by lkankowski** [comment]
Hello.
Thank you for comment, and sorry for late answer :)

I was thinking about this at the beginning of this project, but decided that it will duplicate functionality of Home Apps like Domoticz/Home Assistant - scenes and groups.
The principle doing this project was keep it simple as possible to work autonomously (without Home App). More sophisticated functionality will be in Home App.
