### ISSUE TITLE
Add second expander

### ISSUE THREAD

**Issue by ghost** [lkankowski/arduino-multi-relay#4]
Hi
Can you add manual showing how add step by step second expander ? I read your manual but i dont know how add code:
--- initialize all expanders - expander0.begin(0x20); expander1.begin(0x20); ...
--- change code in before() function - #ifdef USE_EXPANDER ... if ( myRelayButtons[i].relay & 0x0200 ) {... expander1.pinMode ...
--- change code in changeRelayState() function - #ifdef USE_EXPANDER ... if ( myRelayButtons[i].relay & 0x0200 ) {... expander1.digitalWrite( ...

I done but not working
[arduino-multi-relay.zip](https://github.com/lkankowski/arduino-multi-relay/files/2753088/arduino-multi-relay.zip)

**Comment by lkankowski** [comment]
Hello,

Everything looks good, except this one:
   `expander1.begin(0x20);`
Number must be different than the first expander, because it is connected to the same pins through i2c - on expander you can change number using jumpers.

**Comment by ghost** [comment]
Ok but when I try compile it I have an error.

I change jumper on pcb...

**Comment by lkankowski** [comment]
You have syntax errors - here is fixed version
[arduino-multi-relay.zip](https://github.com/lkankowski/arduino-multi-relay/files/2761474/arduino-multi-relay.zip)

**Comment by ghost** [comment]
very very thanks....
