### ISSUE TITLE
Home Assistan logs

### ISSUE THREAD

**Issue by ghost** [lkankowski/arduino-multi-relay#8]
Hi
I have disabled in sketch debug and still on Home Assistan generated after restart HA this logs:
child_id 27 already exists in children of node 0, cannot add child
14:38 __main__.py (WARNING)
child_id 26 already exists in children of node 0, cannot add child
14:38 __main__.py (WARNING)
child_id 25 already exists in children of node 0, cannot add child
14:38 __main__.py (WARNING)
child_id 24 already exists in children of node 0, cannot add child
14:38 __main__.py (WARNING)
child_id 23 already exists in children of node 0, cannot add child
14:38 __main__.py (WARNING)
child_id 22 already exists in children of node 0, cannot add child
14:38 __main__.py (WARNING)
child_id 21 already exists in children of node 0, cannot add child
14:38 __main__.py (WARNING)
child_id 20 already exists in children of node 0, cannot add child
14:38 __main__.py (WARNING)
child_id 19 already exists in children of node 0, cannot add child
14:38 __main__.py (WARNING)
child_id 18 already exists in children of node 0, cannot add child
14:38 __main__.py (WARNING)
child_id 17 already exists in children of node 0, cannot add child
14:38 __main__.py (WARNING)
child_id 16 already exists in children of node 0, cannot add child
14:38 __main__.py (WARNING)
child_id 15 already exists in children of node 0, cannot add child
14:38 __main__.py (WARNING)
child_id 14 already exists in children of node 0, cannot add child
14:38 __main__.py (WARNING)
child_id 12 already exists in children of node 0, cannot add child
14:38 __main__.py (WARNING) - message first occured at 14:38 and shows up 2 times
child_id 10 already exists in children of node 0, cannot add child
14:38 __main__.py (WARNING)
child_id 8 already exists in children of node 0, cannot add child
14:38 __main__.py (WARNING) - message first occured at 14:38 and shows up 2 times
child_id 7 already exists in children of node 0, cannot add child
14:38 __main__.py (WARNING)
child_id 6 already exists in children of node 0, cannot add child
14:38 __main__.py (WARNING)
child_id 5 already exists in children of node 0, cannot add child
14:38 __main__.py (WARNING)
child_id 4 already exists in children of node 0, cannot add child
14:38 __main__.py (WARNING)
child_id 3 already exists in children of node 0, cannot add child
14:38 __main__.py (WARNING)
child_id 2 already exists in children of node 0, cannot add child
14:38 __main__.py (WARNING)
child_id 1 already exists in children of node 0, cannot add child
14:38 __main__.py (WARNING)
child_id 0 already exists in children of node 0, cannot add child
14:38 __main__.py (WARNING)

Where is a problem and how we can resolved this?

This is my config:
mysensors:
  gateways:
    - device: '/dev/serial/by-id/usb-Arduino__www.arduino.cc__0042_85733323739351405131-if00'
      persistence_file: '/config/mysensors_parter.json'
      baud_rate: 115200
  optimistic: false
  persistence: true
  version: '2.2'

**Comment by lkankowski** [comment]
Please paste here current config of sketch or even whole sketch with your customizations.

**Comment by lkankowski** [comment]
Resolved. It is probably normal HA and MySensors sketch behavior.
