### ISSUE TITLE
Impulse_relay state bug

### ISSUE THREAD

**Issue by pemol13** [lkankowski/arduino-multi-relay#9]
The Impulse_relay works correctly, but after pressing the button, button state is set to High and remains unchanged even when the function turns off the relay. The button must be pressed for the second time to change its state to low (relay does not react) and then it all goes from the beginnig in this two-click cycle. If the button is not clicked for the second time (reset to low state) and arduino resets, it sets the relay in the high state (turned on), button must be clicked to turn it off and the main cycle repeats.

**Comment by lkankowski** [comment]
Please, paste here whole your configuration file.

**Comment by lkankowski** [comment]
Newer mind. I've just found a bug and in a few minutes it will be published. I've didn't tested the code - I've found the bug by code analysis and just tested if it compile with my configuration. Use it at your own risk :)

**Comment by lkankowski** [comment]
Fixed and mergedto master
